### PR TITLE
Da 88 visibility issues

### PR DESCRIPTION
**Pull request by a7med-hamdy**
waiting to see if it is fixed

### CODE REVIEW

**Comment by mohamedezzat2000z** [comment]
@a7med-hamdy the bug is gone but the text is too small

**Comment by a7med-hamdy** [comment]
I made it bigger

**Comment by mohamedezzat2000z** [comment]
@a7med-hamdy yes it is better now

**Comment by a7med-hamdy** [comment]
@aaserfawzy  waiting for you to approve and merge

**Review by aaserfawzy — APPROVED** [review]
no problem arise

**Pull request merged**
