### PR TITLE
Da 85 sound integration

### PR DESCRIPTION
**Pull request by Ahmed-Ashour-2024**
Added special music for BOSS levels
Some sound volumes are modified and balanced

### CODE REVIEW

**Comment by Ahmed-Ashour-2024** [comment]
are Sounds good now? Check them

**Comment by Ahmed-Ashour-2024** [comment]
@aaserfawzy _The boss music_ is here to be integrated

**Comment by MariamOsman21** [comment]
yes the sounds are good, Good Job. @Ahmed-Ashour-2024

**Review by aaserfawzy — APPROVED** [review]
Sounds good !!

**Pull request merged**
