### PR TITLE
Da 85 sound integration

### PR DESCRIPTION
**Pull request by mohamedezzat2000z**
finished sound integration with the game

### CODE REVIEW

**Comment by a7med-hamdy** [comment]
did you check the profile for coins and story progress?

**Comment by mohamedezzat2000z** [comment]
> did you check the profile for coins and story progress?
restored everything back in the last commit

**Comment by a7med-hamdy** [comment]
nice approving now

**Review by a7med-hamdy — APPROVED** [review]
game is finished waiting for compilation

**Pull request merged**
